source: /docs
paths:
  uploads: docs
  static: docs
  collections: ''
  data: ''
  layouts:
collections_config:
  docs:
    path: docs
    output: true
    url: '"/[full_slug]/"'
    filter:
    parse_branch_index:
    name:
    description: ''
    icon: notes
    documentation:
    preview:
    sort:
    sort_options:
    singular_name:
    singular_key:
    _editables: {}
    _inputs: {}
    _select_data: {}
    _structures: {}
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas: {}
    schema_key:
_enabled_editors:
  - visual
  - content
  - data
_inputs: {}
_select_data: {}
_structures: {}
_editables: {}
data_config: {}
timezone: Etc/UTC
